import { AlertTriangle, ArrowUpRight, Check, ChevronRight, Info, ShieldAlert, Sparkles } from "lucide-react";
import type { Alert, Route } from "@/lib/offshore-types";

type DecisionPanelProps = { routes: Route[]; selectedRoute: Route; alerts: Alert[]; onSelectRoute: (id: string) => void; onFocusAlert: (alert: Alert) => void };

const toneFor = (score: number) => score < 0.3 ? "low" : score < 0.5 ? "moderate" : "high";

export default function DecisionPanel({ routes, selectedRoute, alerts, onSelectRoute, onFocusAlert }: DecisionPanelProps) {
  return <aside className="decision-panel">
    <section className="panel-section route-results"><div className="panel-kicker"><span>ROUTE OPTIONS</span><span className="result-count">{routes.length} candidates</span></div><div className="route-cards">{routes.map((route) => <button className={`route-card ${route.id === selectedRoute.id ? "selected" : ""}`} key={route.id} onClick={() => onSelectRoute(route.id)}><div className="route-card-top"><span className={`route-mark ${route.accent}`} /><div><strong>{route.name}</strong><small>{route.objective}</small></div>{route.id === selectedRoute.id && <Check size={15} className="route-check" />}</div><div className="route-metrics"><span><b>{route.distanceKm.toLocaleString()}</b> km</span><span><b>{route.etaHours}</b> h</span><span><b>{Math.round(route.riskScore * 100)}</b><i className={toneFor(route.riskScore)}>/100</i></span></div><div className="route-foot"><span>{route.exposure}</span><ArrowUpRight size={13} /></div></button>)}</div></section>
    <section className="panel-section selected-route"><div className="panel-kicker"><span>SELECTED ROUTE</span><span className="live-tag"><i /> live model</span></div><div className="selected-route-header"><div><h3>{selectedRoute.name} · {selectedRoute.objective}</h3><p>{selectedRoute.status}</p></div><span className="risk-badge"><b>{Math.round(selectedRoute.riskScore * 100)}</b><small>risk score</small></span></div><div className="big-metrics"><div><strong>{selectedRoute.distanceKm.toLocaleString()}</strong><span>distance · km</span></div><div><strong>{selectedRoute.etaHours}<small>h</small></strong><span>estimated ETA</span></div><div><strong>{Math.round(selectedRoute.fuelLitres / 1000)}k</strong><span>fuel · litres</span></div></div></section>
    <section className="panel-section explanation"><div className="panel-kicker"><span><Sparkles size={13} /> WHY THIS ROUTE?</span><span className="confidence">moderate confidence</span></div><p><b>{selectedRoute.name}</b> is recommended for the current <b>{selectedRoute.objective.toLowerCase()}</b> priority because it keeps predicted iceberg exposure below the fastest option while adding only a small transit-time trade-off.</p><ul><li><Check size={13} /> 34% lower predicted iceberg exposure</li><li><Check size={13} /> Moderate sea-ice concentration in corridor</li><li><Check size={13} /> 7 h faster than the lowest-risk option</li></ul></section>
    <section className="panel-section alert-section"><div className="panel-kicker"><span><ShieldAlert size={13} /> ROUTE ALERTS</span><span className="alert-count">{alerts.filter((alert) => alert.severity === "high").length} high</span></div>{alerts.slice(0, 2).map((alert) => <button className={`alert-row ${alert.severity}`} key={alert.id} onClick={() => onFocusAlert(alert)}><span className="alert-icon">{alert.severity === "high" ? <AlertTriangle size={15} /> : <Info size={15} />}</span><span><strong>{alert.title}</strong><small>{alert.time} · {alert.hazardType}</small></span><ChevronRight size={14} /></button>)}</section>
    <div className="panel-disclaimer"><AlertTriangle size={13} /><span>Decision support only. Forecasts and route metrics are estimates, not autonomous navigation instructions.</span></div>
  </aside>;
}
