import asyncio as _aio
import uuid
from typing import Any, Optional

from app.api import deps
from app.models.alert import Alert
from app.models.enums import AlertSeverity
from app.repositories.alert import alert as alert_repo
from app.schemas.alert import AlertCreate, AlertProperties, AlertResponse
from app.schemas.common import GeoJSONFeature, GeoJSONFeatureCollection
from app.utils.geojson import parse_wkt_point, to_geojson_geometry
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession

router = APIRouter()


@router.get("/", response_model=GeoJSONFeatureCollection[AlertResponse])
async def get_alerts(
    route_id: Optional[uuid.UUID] = None,
    severity: Optional[AlertSeverity] = None,
    alert_type: Optional[str] = None,
    db: AsyncSession = Depends(deps.get_db),
    pagination: deps.PaginationParams = Depends(),
    time_range: deps.TimeRangeParams = Depends(),
) -> Any:
    """List alerts with optional filtering by route, severity, type, and time."""
    filters = dict(
        route_id=route_id,
        severity=severity.value if severity else None,
        alert_type=alert_type,
        start_time=time_range.start_time,
        end_time=time_range.end_time,
    )

    # FIX: fire get_multi and count concurrently — halves DB round-trips vs
    # the previous two sequential awaits with identical WHERE clauses.
    rows, total = await _aio.gather(
        alert_repo.get_multi(db, skip=pagination.skip, limit=pagination.limit, **filters),
        alert_repo.count(db, **filters),
    )

    features = [
        GeoJSONFeature[AlertResponse](
            type="Feature",
            geometry=to_geojson_geometry(row.location),
            properties=AlertProperties(
                id=row.id,
                alert_type=row.alert_type,
                severity=row.severity,
                timestamp=row.timestamp,
                route_id=row.route_id,
                hazard_source=row.hazard_source,
                message=row.message,
                status=row.status,
                triggering_metric=row.triggering_metric,
                threshold=row.threshold,
                confidence=row.confidence,
            ),
        )
        for row in rows
    ]
    return GeoJSONFeatureCollection[AlertResponse](
        features=features,
        total=total,
        skip=pagination.skip,
        limit=pagination.limit,
    )


@router.post("/", response_model=AlertResponse, status_code=status.HTTP_201_CREATED)
async def create_alert(
    payload: AlertCreate,
    db: AsyncSession = Depends(deps.get_db),
) -> Any:
    """Persist an alert (e.g., generated by the orchestrator or a worker)."""
    try:
        parse_wkt_point(payload.location)
    except Exception as exc:
        raise HTTPException(
            status_code=422, detail=f"location must be a WKT POINT: {exc}"
        )
    obj = Alert(
        alert_type=payload.alert_type,
        severity=payload.severity,
        location=payload.location,
        timestamp=payload.timestamp,
        route_id=payload.route_id,
        hazard_source=payload.hazard_source,
        message=payload.message,
        status=payload.status or "active",
        triggering_metric=payload.triggering_metric,
        threshold=payload.threshold,
        confidence=payload.confidence,
    )
    db.add(obj)
    await db.commit()
    await db.refresh(obj)
    return GeoJSONFeature[AlertResponse](
        type="Feature",
        geometry=to_geojson_geometry(obj.location),
        properties=AlertProperties(
            id=obj.id,
            alert_type=obj.alert_type,
            severity=obj.severity,
            timestamp=obj.timestamp,
            route_id=obj.route_id,
            hazard_source=obj.hazard_source,
            message=obj.message,
            status=obj.status,
            triggering_metric=obj.triggering_metric,
            threshold=obj.threshold,
            confidence=obj.confidence,
        ),
    )
