"""phase2

Revision ID: 6365a5d41309
Revises: 
Create Date: 2026-09-03 01:15:24.592144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '6365a5d41309'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icebergs',
    sa.Column('iceberg_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('iceberg_id')
    )
    op.create_table('ocean_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('current_speed', sa.Float(), nullable=False),
    sa.Column('current_direction', sa.Float(), nullable=False),
    sa.Column('sea_surface_temperature', sa.Float(), nullable=False),
    sa.Column('wave_information', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocean_observations_geometry'), 'ocean_observations', ['geometry'], unique=False)
    op.create_index(op.f('ix_ocean_observations_timestamp'), 'ocean_observations', ['timestamp'], unique=False)
    op.create_table('risk_cells',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ice_risk', sa.Float(), nullable=False),
    sa.Column('iceberg_risk', sa.Float(), nullable=False),
    sa.Column('weather_risk', sa.Float(), nullable=False),
    sa.Column('current_risk', sa.Float(), nullable=False),
    sa.Column('composite_risk', sa.Float(), nullable=False),
    sa.Column('risk_category', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_cells_geometry'), 'risk_cells', ['geometry'], unique=False)
    op.create_index(op.f('ix_risk_cells_timestamp'), 'risk_cells', ['timestamp'], unique=False)
    op.create_table('sea_ice_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('concentration', sa.Float(), nullable=False),
    sa.Column('thickness', sa.Float(), nullable=True),
    sa.Column('ice_type', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('data_quality', sa.Float(), nullable=True, comment='Confidence score 0-1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sea_ice_observations_geometry'), 'sea_ice_observations', ['geometry'], unique=False)
    op.create_index(op.f('ix_sea_ice_observations_timestamp'), 'sea_ice_observations', ['timestamp'], unique=False)
    op.create_table('vessels',
    sa.Column('vessel_id', sa.Uuid(), nullable=False),
    sa.Column('vessel_name', sa.String(length=255), nullable=False),
    sa.Column('vessel_type', sa.String(length=100), nullable=False),
    sa.Column('cruising_speed', sa.Float(), nullable=False, comment='in knots'),
    sa.Column('fuel_consumption', sa.Float(), nullable=False, comment='rate of consumption'),
    sa.Column('ice_capability', sa.String(length=50), nullable=False, comment='ice class'),
    sa.Column('operational_limits', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('vessel_id')
    )
    op.create_index(op.f('ix_vessels_vessel_name'), 'vessels', ['vessel_name'], unique=False)
    op.create_table('weather_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=False),
    sa.Column('wind_direction', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('wave_height', sa.Float(), nullable=False),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_observations_geometry'), 'weather_observations', ['geometry'], unique=False)
    op.create_index(op.f('ix_weather_observations_timestamp'), 'weather_observations', ['timestamp'], unique=False)
    op.create_table('iceberg_detections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('iceberg_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('estimated_size', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_imagery', sa.String(length=255), nullable=True),
    sa.Column('detection_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['iceberg_id'], ['icebergs.iceberg_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iceberg_detections_geometry'), 'iceberg_detections', ['geometry'], unique=False)
    op.create_index(op.f('ix_iceberg_detections_iceberg_id'), 'iceberg_detections', ['iceberg_id'], unique=False)
    op.create_index(op.f('ix_iceberg_detections_timestamp'), 'iceberg_detections', ['timestamp'], unique=False)
    op.create_table('iceberg_predictions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('iceberg_id', sa.Uuid(), nullable=False),
    sa.Column('prediction_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('forecast_horizon', sa.Integer(), nullable=False, comment='Forecast horizon in seconds/hours'),
    sa.Column('predicted_geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('uncertainty_representation', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('model_confidence', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['iceberg_id'], ['icebergs.iceberg_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iceberg_predictions_iceberg_id'), 'iceberg_predictions', ['iceberg_id'], unique=False)
    op.create_index(op.f('ix_iceberg_predictions_predicted_geometry'), 'iceberg_predictions', ['predicted_geometry'], unique=False)
    op.create_index(op.f('ix_iceberg_predictions_prediction_timestamp'), 'iceberg_predictions', ['prediction_timestamp'], unique=False)
    op.create_table('routes',
    sa.Column('route_id', sa.Uuid(), nullable=False),
    sa.Column('origin', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('vessel_id', sa.Uuid(), nullable=False),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False, comment='distance in nautical miles'),
    sa.Column('eta', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estimated_fuel', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('objective_type', sa.Enum('FASTEST', 'SAFEST', 'FUEL_EFFICIENT', name='objectivetype'), nullable=False),
    sa.Column('algorithm_version', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.vessel_id'], ),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_index(op.f('ix_routes_geometry'), 'routes', ['geometry'], unique=False)
    op.create_index(op.f('ix_routes_vessel_id'), 'routes', ['vessel_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('route_id', sa.Uuid(), nullable=True),
    sa.Column('hazard_source', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.route_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_location'), 'alerts', ['location'], unique=False)
    op.create_index(op.f('ix_alerts_route_id'), 'alerts', ['route_id'], unique=False)
    op.create_index(op.f('ix_alerts_timestamp'), 'alerts', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_timestamp'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_route_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_location'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_routes_vessel_id'), table_name='routes')
    op.drop_index(op.f('ix_routes_geometry'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_iceberg_predictions_prediction_timestamp'), table_name='iceberg_predictions')
    op.drop_index(op.f('ix_iceberg_predictions_predicted_geometry'), table_name='iceberg_predictions')
    op.drop_index(op.f('ix_iceberg_predictions_iceberg_id'), table_name='iceberg_predictions')
    op.drop_table('iceberg_predictions')
    op.drop_index(op.f('ix_iceberg_detections_timestamp'), table_name='iceberg_detections')
    op.drop_index(op.f('ix_iceberg_detections_iceberg_id'), table_name='iceberg_detections')
    op.drop_index(op.f('ix_iceberg_detections_geometry'), table_name='iceberg_detections')
    op.drop_table('iceberg_detections')
    op.drop_index(op.f('ix_weather_observations_timestamp'), table_name='weather_observations')
    op.drop_index(op.f('ix_weather_observations_geometry'), table_name='weather_observations')
    op.drop_table('weather_observations')
    op.drop_index(op.f('ix_vessels_vessel_name'), table_name='vessels')
    op.drop_table('vessels')
    op.drop_index(op.f('ix_sea_ice_observations_timestamp'), table_name='sea_ice_observations')
    op.drop_index(op.f('ix_sea_ice_observations_geometry'), table_name='sea_ice_observations')
    op.drop_table('sea_ice_observations')
    op.drop_index(op.f('ix_risk_cells_timestamp'), table_name='risk_cells')
    op.drop_index(op.f('ix_risk_cells_geometry'), table_name='risk_cells')
    op.drop_table('risk_cells')
    op.drop_index(op.f('ix_ocean_observations_timestamp'), table_name='ocean_observations')
    op.drop_index(op.f('ix_ocean_observations_geometry'), table_name='ocean_observations')
    op.drop_table('ocean_observations')
    op.drop_table('icebergs')
    # ### end Alembic commands ###
