"""Add metrics to alerts

Revision ID: af67bc01aa13
Revises: 6365a5d41309
Create Date: 2026-09-03 19:10:18.408636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'af67bc01aa13'
down_revision: Union[str, None] = '6365a5d41309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('triggering_metric', sa.Float(), nullable=True))
    op.add_column('alerts', sa.Column('threshold', sa.Float(), nullable=True))
    op.add_column('alerts', sa.Column('confidence', sa.Float(), nullable=True))
    op.alter_column('alerts', 'location',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True),
               type_=geoalchemy2.types.Geometry(srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False),
               existing_nullable=False)
    op.add_column('risk_cells', sa.Column('confidence_score', sa.Float(), nullable=False))
    op.add_column('risk_cells', sa.Column('missing_data_flags', sa.JSON(), nullable=False))
    op.add_column('risk_cells', sa.Column('metadata_info', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_cells', 'metadata_info')
    op.drop_column('risk_cells', 'missing_data_flags')
    op.drop_column('risk_cells', 'confidence_score')
    op.alter_column('alerts', 'location',
               existing_type=geoalchemy2.types.Geometry(srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False),
               type_=geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True),
               existing_nullable=False)
    op.drop_column('alerts', 'confidence')
    op.drop_column('alerts', 'threshold')
    op.drop_column('alerts', 'triggering_metric')
    # ### end Alembic commands ###
